version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: django
    container_name: django_chat_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data: